# Generated by Django 5.1.3 on 2024-12-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initialinfo',
            old_name='referell_code',
            new_name='referal_code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='referell_code',
            new_name='referal_code',
        ),
    ]
