# Generated by Django 5.1.3 on 2025-03-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='referal_code',
            new_name='referral_code',
        ),
    ]
