# Generated by Django 5.1.3 on 2024-12-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initialinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='mobile',
        ),
    ]
