# Generated by Django 5.1.3 on 2024-12-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_phone_number_user_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='referell_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
