# Generated by Django 5.1.3 on 2025-02-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bmu',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
