# Generated by Django 5.1.3 on 2025-03-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_rename_date_rating_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.FloatField(default=0, help_text='Discount percentage for the deal.')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('main_products', models.ManyToManyField(related_name='deals', to='product.mainproduct')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
