# Generated by Django 5.1.3 on 2025-03-19 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealoftheweek', '0001_initial'),
        ('product', '0005_rename_date_rating_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealoftheweek',
            name='main_products',
        ),
        migrations.AddField(
            model_name='dealoftheweek',
            name='main_products',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='product.mainproduct'),
            preserve_default=False,
        ),
    ]
