# Generated by Django 5.1.3 on 2025-03-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, to='category.category'),
        ),
    ]
