# Generated by Django 5.1.3 on 2025-03-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_coupon_applicable_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='usage_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
