# Generated by Django 5.1.3 on 2025-03-21 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_couponusage_usage_count'),
        ('order', '0003_alter_order_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponusage',
            name='usage_count',
        ),
        migrations.AddField(
            model_name='couponusage',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='order.order'),
            preserve_default=False,
        ),
    ]
