# Generated by Django 5.1.3 on 2025-03-22 07:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_remove_couponusage_usage_count_couponusage_order'),
        ('order', '0003_alter_order_tracking_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together={('user', 'coupon', 'order')},
        ),
    ]
