# Generated by Django 5.1.3 on 2024-12-14 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_description', models.TextField()),
                ('ribbon', models.CharField(max_length=100)),
                ('threshold', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('whats_included', models.TextField()),
                ('vedio_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MainProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.mainproduct')),
            ],
        ),
    ]
