# Generated by Django 5.1.3 on 2025-02-27 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attribute', '0001_initial'),
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('plant', 'plant'), ('seed', 'seed'), ('pot', 'Pot'), ('tool', 'Garden Tool')], default='plant', max_length=10)),
                ('default_sale_price', models.FloatField(default=0)),
                ('default_price', models.FloatField(default=0)),
                ('default_discount', models.FloatField(default=0)),
                ('default_sku', models.FloatField(default=0)),
                ('short_description', models.TextField()),
                ('ribbon', models.CharField(max_length=100)),
                ('threshold', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('whats_included', models.TextField()),
                ('vedio_link', models.CharField(max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_seasonal_collection', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MainProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main_product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.mainproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litre', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.FloatField(default=0)),
                ('sale_price', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('sku', models.CharField(max_length=40)),
                ('image', models.ImageField(default='default/category_default.jpg', upload_to='product_images/')),
                ('visible_online', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('blade_material_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.bladematerial')),
                ('color_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.color')),
                ('handle_material_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.handlematerial')),
                ('material_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.material')),
                ('planter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.planter')),
                ('planter_size_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.plantersize')),
                ('pot_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.pottype')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.mainproduct')),
                ('shape_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.shape')),
                ('size_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.size')),
                ('weight_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.weight')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.mainproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.mainproduct')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.mainproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('main_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.mainproduct')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_review', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('main_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.mainproduct')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
