# Generated by Django 5.1.3 on 2025-02-28 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_litre'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='litre',
        ),
        migrations.AddField(
            model_name='product',
            name='litre_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.litre'),
        ),
    ]
