# Generated by Django 5.1.3 on 2025-03-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_litre_product_litre_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='add_ons',
            field=models.ManyToManyField(blank=True, to='product.mainproduct'),
        ),
    ]
