# Generated by Django 5.1.3 on 2024-12-20 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0007_alter_planter_planter_size'),
        ('product', '0002_productcategory_productsubcategory_producttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproductimage',
            name='image',
            field=models.ImageField(upload_to='main_product_images/'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=10)),
                ('sale_price', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('profit', models.CharField(max_length=10)),
                ('discount', models.CharField(max_length=10)),
                ('stock', models.CharField(max_length=10)),
                ('sku', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('visible_online', models.BooleanField(default=True)),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.color')),
                ('planter_size_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.plantersize')),
                ('plnater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.planter')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.mainproduct')),
                ('size_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.size')),
            ],
        ),
    ]
