# Generated by Django 5.1.3 on 2024-12-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_mainproductimage_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default/category_default.jpg', upload_to='product_images/'),
        ),
    ]
