# Generated by Django 5.1.3 on 2025-03-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productviewcount_recentlyviewedproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='rating',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='recommend',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.CharField(default='Untitled Review', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='product_review',
            field=models.TextField(max_length=300),
        ),
    ]
