# Generated by Django 5.1.3 on 2024-12-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='plnater_id',
            new_name='planter_id',
        ),
    ]
