# Generated by Django 5.1.3 on 2025-03-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_date_rating_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='discounted_price',
        ),
    ]
