# Generated by Django 5.1.3 on 2024-12-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_plnater_id_product_planter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='is_seasonal_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
