# Generated by Django 5.1.3 on 2024-12-25 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_mainproduct_is_best_seller_mainproduct_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproductimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.mainproduct'),
        ),
    ]
