# Generated by Django 5.1.3 on 2025-02-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='default_price',
            field=models.FloatField(default=0),
        ),
    ]
