# Generated by Django 5.1.3 on 2025-03-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_discount_product_discounted_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='mrp',
        ),
    ]
