# Generated by Django 5.1.3 on 2025-03-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_price_product_mrp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='discount_amount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sale_price',
            new_name='selling_price',
        ),
    ]
