# Generated by Django 5.1.3 on 2024-12-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_mainproductimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
