# Generated by Django 5.1.3 on 2025-02-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_mainproduct_default_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='default_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='default_sale_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='default_sku',
            field=models.FloatField(default=0),
        ),
    ]
