# Generated by Django 5.1.3 on 2025-03-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_discounted_price_product_discount_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainproduct',
            old_name='default_discount',
            new_name='default_discount_amount',
        ),
        migrations.RenameField(
            model_name='mainproduct',
            old_name='default_price',
            new_name='default_mrp',
        ),
        migrations.RenameField(
            model_name='mainproduct',
            old_name='default_sale_price',
            new_name='default_selling_price',
        ),
    ]
