# Generated by Django 5.1.3 on 2025-02-27 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0016_bladematerial_handlematerial_material_pottype_shape'),
        ('product', '0008_mainproduct_default_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='blade_material_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.bladematerial'),
        ),
        migrations.AddField(
            model_name='product',
            name='handle_material_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.handlematerial'),
        ),
        migrations.AddField(
            model_name='product',
            name='litre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.material'),
        ),
        migrations.AddField(
            model_name='product',
            name='pot_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.pottype'),
        ),
        migrations.AddField(
            model_name='product',
            name='shape_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.shape'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='type',
            field=models.CharField(choices=[('plant', 'plant'), ('seed', 'seed'), ('pot', 'Pot'), ('tool', 'Garden Tool')], default='plant', max_length=10),
        ),
    ]
