# Generated by Django 5.1.3 on 2024-12-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='type',
            field=models.CharField(choices=[('plant', 'plant'), ('seed', 'seed')], default='plant', max_length=10),
        ),
    ]
