# Generated by Django 5.1.3 on 2024-12-27 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0010_alter_weight_size_grams'),
        ('product', '0009_mainproduct_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.weight'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='planter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.planter'),
        ),
        migrations.AlterField(
            model_name='product',
            name='planter_size_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.plantersize'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.size'),
        ),
    ]
