# Generated by Django 5.1.3 on 2025-02-27 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0016_bladematerial_handlematerial_material_pottype_shape'),
        ('product', '0009_product_blade_material_id_product_handle_material_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='planter_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.planter'),
        ),
        migrations.AlterField(
            model_name='product',
            name='planter_size_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.plantersize'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.weight'),
        ),
    ]
