# Generated by Django 5.1.3 on 2025-03-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_default_discount_mainproduct_default_discount_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_amount',
            new_name='discount',
        ),
    ]
