# Generated by Django 5.1.3 on 2025-03-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_discount_amount_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainproduct',
            old_name='default_discount_amount',
            new_name='default_discount',
        ),
    ]
