# Generated by Django 5.1.3 on 2024-11-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contact_no', models.IntegerField()),
                ('services', models.TextField()),
                ('location', models.TextField()),
                ('message', models.TextField()),
                ('comment', models.TextField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Visible', models.BooleanField(default=False)),
                ('Heading', models.TextField()),
            ],
        ),
    ]
