# Generated by Django 5.1.3 on 2024-12-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelist',
            name='title',
            field=models.CharField(default='default_title', max_length=100),
        ),
    ]
