# Generated by Django 5.1.3 on 2024-12-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default/category_default.png', upload_to='category/'),
        ),
    ]
