# Generated by Django 5.1.3 on 2025-02-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default='default/category_default.png', upload_to='subcategory/'),
        ),
    ]
