# Generated by Django 5.1.3 on 2025-02-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('Tech Positions', 'Tech Positions'), ('Non-Tech Positions', 'Non-Tech Positions')], default='Non-Tech Positions', max_length=30)),
                ('position_name', models.CharField(max_length=100)),
                ('job_summary', models.TextField()),
                ('responsibilities', models.TextField()),
                ('desired_skills', models.TextField()),
            ],
        ),
    ]
