# Generated by Django 5.1.3 on 2024-12-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='categories',
            field=models.CharField(choices=[('Tech Positions', 'Tech Positions'), ('Non-Tech Positions', 'Non-Tech Positions')], default='Non-Tech Positions', max_length=30),
        ),
    ]
