# Generated by Django 5.1.3 on 2025-02-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0015_alter_planter_name_alter_planter_unique_together'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='potvariant',
            name='unique_pot_variant',
        ),
        migrations.RemoveConstraint(
            model_name='toolvariant',
            name='unique_tool_variant',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='material',
            new_name='material_id',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='shape',
            new_name='shape_id',
        ),
        migrations.RenameField(
            model_name='potvariant',
            old_name='color',
            new_name='color_id',
        ),
        migrations.RenameField(
            model_name='potvariant',
            old_name='inventory_item',
            new_name='inventory_item_id',
        ),
        migrations.RenameField(
            model_name='potvariant',
            old_name='pot_type',
            new_name='pot_type_id',
        ),
        migrations.RenameField(
            model_name='potvariant',
            old_name='size',
            new_name='size_id',
        ),
        migrations.RenameField(
            model_name='toolvariant',
            old_name='blade_material',
            new_name='blade_material_id',
        ),
        migrations.RenameField(
            model_name='toolvariant',
            old_name='color',
            new_name='color_id',
        ),
        migrations.RenameField(
            model_name='toolvariant',
            old_name='handle_material',
            new_name='handle_material_id',
        ),
        migrations.RenameField(
            model_name='toolvariant',
            old_name='inventory_item',
            new_name='inventory_item_id',
        ),
        migrations.RenameField(
            model_name='toolvariant',
            old_name='size',
            new_name='size_id',
        ),
        migrations.AddField(
            model_name='potvariant',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toolvariant',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='potvariant',
            constraint=models.UniqueConstraint(fields=('inventory_item_id', 'size_id', 'color_id', 'pot_type_id', 'litre'), name='unique_pot_variant'),
        ),
        migrations.AddConstraint(
            model_name='toolvariant',
            constraint=models.UniqueConstraint(fields=('inventory_item_id', 'size_id', 'color_id', 'handle_material_id', 'blade_material_id'), name='unique_tool_variant'),
        ),
    ]
