# Generated by Django 5.1.6 on 2025-02-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_banner', models.ImageField(upload_to='banners/mobileBanner/')),
                ('web_banner', models.ImageField(upload_to='banners/webBanner/')),
                ('type', models.CharField(max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=100)),
            ],
        ),
    ]
