# Generated by Django 5.1.3 on 2024-12-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_banner', models.ImageField(upload_to='banners/mobileBanner/')),
                ('web_banner', models.ImageField(upload_to='banners/webBanner/')),
                ('type', models.CharField(max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
