# Generated by Django 5.1.3 on 2024-12-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
