# Generated by Django 5.1.3 on 2025-03-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_mainproduct_add_ons'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='default/combo_default.jpg', upload_to='combo_images/')),
                ('total_price', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('final_price', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='combo_offers', to='product.product')),
            ],
        ),
    ]
