# Generated by Django 5.1.3 on 2025-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combooffer',
            name='discount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='combooffer',
            name='final_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='combooffer',
            name='total_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
