# Generated by Django 5.1.3 on 2025-03-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combo', '0003_alter_combooffer_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combooffer',
            name='final_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='combooffer',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
