# Generated by Django 5.1.3 on 2025-03-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combo', '0004_alter_combooffer_final_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combooffer',
            name='is_shop_the_look',
            field=models.BooleanField(default=False),
        ),
    ]
