# Generated by Django 5.1.3 on 2024-12-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=30)),
                ('color_code', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
