# Generated by Django 5.1.3 on 2024-12-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
