# Generated by Django 5.1.3 on 2024-12-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0003_alter_size_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planter_id', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
