# Generated by Django 5.1.3 on 2024-12-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0004_planter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanterSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='planter',
            name='planter_id',
        ),
        migrations.AlterField(
            model_name='planter',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='planter',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
