# Generated by Django 5.1.3 on 2024-12-14 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0005_plantersize_remove_planter_planter_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planter',
            name='planter_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attribute.plantersize'),
        ),
    ]
