# Generated by Django 5.1.3 on 2024-12-14 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0006_planter_planter_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planter',
            name='planter_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.plantersize'),
        ),
    ]
