# Generated by Django 5.1.3 on 2024-12-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0007_alter_planter_planter_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_grams', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
