# Generated by Django 5.1.3 on 2024-12-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0008_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
