# Generated by Django 5.1.3 on 2024-12-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0009_alter_weight_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='size_grams',
            field=models.CharField(max_length=50),
        ),
    ]
