# Generated by Django 5.1.3 on 2025-01-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0010_alter_weight_size_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
