# Generated by Django 5.1.3 on 2025-01-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0011_alter_color_color_code_alter_color_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
