# Generated by Django 5.1.3 on 2025-01-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0012_alter_size_name_alter_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantersize',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plantersize',
            name='size',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
