# Generated by Django 5.1.3 on 2025-01-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0013_alter_plantersize_name_alter_plantersize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planter',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
