# Generated by Django 5.1.3 on 2025-01-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0014_alter_planter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planter',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='planter',
            unique_together={('name', 'planter_size')},
        ),
    ]
