# Generated by Django 5.1.3 on 2025-04-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_deliverylocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylocation',
            name='city',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='deliverylocation',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
