# Generated by Django 5.1.3 on 2025-04-13 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_deliverylocation_city_deliverylocation_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylocation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='deliverylocation',
            name='state',
        ),
    ]
