# Generated by Django 5.1.3 on 2025-04-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_deliverylocation_city_deliverylocation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverylocation',
            name='city',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
