# Generated by Django 5.1.3 on 2025-03-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_applied_coupon_order_coupon_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
