# Generated by Django 5.1.3 on 2025-01-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_product_id_order_grand_total_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.FloatField(),
        ),
    ]
