# Generated by Django 5.1.3 on 2025-02-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_deliveryaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='user',
            new_name='user_id',
        ),
    ]
