# Generated by Django 5.1.3 on 2025-03-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_price_orderitem_mrp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('DISPATCHED', 'Dispatched'), ('ON_THE_WAY', 'On the Way'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], max_length=20),
        ),
    ]
