# Generated by Django 5.1.3 on 2025-02-07 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_user_deliveryaddress_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='order_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='order.order'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_user_addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
