# Generated by Django 5.1.3 on 2025-02-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_address_deliveryaddress_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='is_default',
        ),
    ]
