# Generated by Django 5.1.3 on 2025-02-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_deliveryaddress_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Express', 'Express')], default='Standard', max_length=10),
        ),
    ]
