# Generated by Django 5.1.3 on 2025-03-28 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderitem_discount_alter_orderitem_mrp_and_more'),
        ('store', '0002_store_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Express', 'Express'), ('PickUpStore', 'Pick Up Store')], default='Standard', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('PICKUP_COMPLETED', 'Pickup Completed'), ('DISPATCHED', 'Dispatched'), ('ON_THE_WAY', 'On the Way'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned'), ('PICKUP_EXPIRED', 'Pickup Expired')], default='INITIATED', max_length=20),
        ),
    ]
