# Generated by Django 5.1.3 on 2025-04-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_pickup_deadline_order_store_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('PICKUP_COMPLETED', 'Pickup Completed'), ('DISPATCHED', 'Dispatched'), ('ON_THE_WAY', 'On the Way'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_APPROVED', 'Return Approved'), ('RETURN_REJECTED', 'Return Rejected'), ('RETURNED', 'Returned'), ('PICKUP_EXPIRED', 'Pickup Expired')], default='INITIATED', max_length=20),
        ),
    ]
