# Generated by Django 5.1.3 on 2025-03-20 06:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btcoins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BTCoins',
            new_name='BTCoinsWallet',
        ),
    ]
