# Generated by Django 5.1.3 on 2025-03-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcoins', '0002_rename_btcoins_btcoinswallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCoinsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_limit', models.PositiveIntegerField(default=10)),
                ('referral_coins_referrer', models.PositiveIntegerField(default=200)),
                ('referral_coins_referred', models.PositiveIntegerField(default=50)),
                ('max_coins_earned_per_order', models.PositiveIntegerField(default=100)),
                ('max_coins_redeemed_per_order', models.PositiveIntegerField(default=200)),
                ('coin_expiry_days', models.PositiveIntegerField(default=365)),
            ],
        ),
    ]
