# Generated by Django 5.1.3 on 2025-03-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcoins', '0003_btcoinssettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btcoinswallet',
            name='referral_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
