# Generated by Django 5.1.3 on 2025-03-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcoins', '0004_alter_btcoinswallet_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='btcoinssettings',
            name='coins_per_100_rupees',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
